/* CRIANDO A DATABASE */

CREATE DATABASE PRJ_INTEGRATION
GO

/* CONECTANDO A DATABASE */

USE PRJ_INTEGRATION
GO

/* CRIANDO UMA TABELA DE ORIGEM */

CREATE TABLE CLIENTES(
	IDCLIENTE INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(50)
)
GO

INSERT INTO CLIENTES VALUES('CLARA','F','CLARA@GMAIL.COM')
INSERT INTO CLIENTES VALUES('MAFRA','M','MAFRA@GMAIL.COM')
INSERT INTO CLIENTES VALUES('JOAO','M','JOAO@GMAIL.COM')
INSERT INTO CLIENTES VALUES('ANA','F','ANA@GMAIL.COM')
INSERT INTO CLIENTES VALUES('LILIAN','F','LILIAN@GMAIL.COM')
GO

SELECT * FROM CLIENTES
GO

/* update */

UPDATE CLIENTES SET NOME = 'LETICIA'
WHERE NOME = 'ANA'

SELECT * FROM CLIENTES

CREATE TABLE CLIENTES_02(
	IDCLIENTE INT PRIMARY KEY,
	NOME VARCHAR(30),
	EMAIL VARCHAR(50)
)
GO

select * from CLIENTES_02
truncate table CLIENTES_02

 /* verificando os paises */

 select * from Paises


