/* CRIANDO A DATABASE */

CREATE DATABASE PRJ_INTEGRATION
GO

/* CONECTANDO A DATABASE */

USE PRJ_INTEGRATION
GO

/* CRIANDO UMA TABELA DE ORIGEM */

CREATE TABLE CLIENTES(
	IDCLIENTE INT IDENTITY PRIMARY KEY,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(50)
)
GO

INSERT INTO CLIENTES VALUES('CLARA','F','CLARA@GMAIL.COM')
INSERT INTO CLIENTES VALUES('MAFRA','M','MAFRA@GMAIL.COM')
INSERT INTO CLIENTES VALUES('JOAO','M','JOAO@GMAIL.COM')
INSERT INTO CLIENTES VALUES('ANA','F','ANA@GMAIL.COM')
INSERT INTO CLIENTES VALUES('LILIAN','F','LILIAN@GMAIL.COM')
GO

SELECT * FROM CLIENTES
GO

/* update */

UPDATE CLIENTES SET NOME = 'LETICIA'
WHERE NOME = 'ANA'

SELECT * FROM CLIENTES

CREATE TABLE CLIENTES_02(
	IDCLIENTE INT PRIMARY KEY,
	NOME VARCHAR(30),
	EMAIL VARCHAR(50)
)
GO

select * from CLIENTES_02
truncate table CLIENTES_02

 /* verificando os paises */

 select * from Paises


/*---------------*/


CREATE TABLE ALUNOS_CSV(
	IDALUNO INT PRIMARY KEY IDENTITY,
	NOME NVARCHAR(100),
	EMAIL VARCHAR(100)
)
GO

SELECT * FROM ALUNOS_CSV

/* JUNTAR NOME E SOBRENOME
   CONVERTER M = CASADO E S = SOLTEIRO
   CONVERTER M = MASCULINO E F = FEMININO
   SOMENTE PESSOAS COM 2 OU MENOS FILHOS
*/

CREATE TABLE CLIENTES(
	NOME_COMPLETO NVARCHAR(100),
	ESTADO_CIVIL NVARCHAR(20),
	SEXO NVARCHAR(20),
	FILHOS NVARCHAR(5)
)
GO

select COUNT(*) from CLIENTES

delete from clientes





/* EXERCICIO 01

EM UM MESMO PACOTE, UTILIZAR A PLANILHA CUSTOMERS
SEPARACAO POR ESTADO AL, AZ, CA, CO
NOME E SOBRENOME (CONCATENADOS)
City
State
Education
Lake Oswego
TotalChildren

AL - BANCO CHAMADO CLIENTES_AL -> TABELA CLI_AL
AZ - PLANILHA DO EXCEL
CA - FLAT FILE
CO - LIVRE */






